config/routes.rb
DreamTeam::Application.routes.draw do

  # Admin-only routes
  unless Rails.env.production?
    namespace :admin do
      root :to => "sports#index"
      resources :sports
      resources :projects
      resources :picks
      resources :readers
      resources :unit_actions

      scope ":sport" do
        resources :leagues
        resources :conferences
        resources :divisions
        resources :teams
        resources :players
      end
    end
  end


  scope ":project" do
    resources :picks
    post "picks/update", :to => "picks#update", :as => "update_picks"
    resources :readers
    resources :players
    resources :teams

  end

end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :abbreviation, :name, :slug, :sport_id
  has_many :conferences
  has_many :teams
  belongs_to :sport

  validates_presence_of :abbreviation, :sport

  include Sluggish
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < Admin::ApplicationController
  before_filter :find_league, :except => [:index, :new, :create]

  # GET /admin/leagues
  # GET /admin/leagues.json
  def index
    @leagues = @sport.leagues

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leagues }
    end
  end

  # GET /admin/leagues/1
  # GET /admin/leagues/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @league }
    end
  end

  # GET /admin/leagues/new
  # GET /admin/leagues/new.json
  def new
    @league = @sport.leagues.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  # GET /admin/leagues/1/edit
  def edit
  end

  # POST /admin/leagues
  # POST /admin/leagues.json
  def create
    @league = @sport.leagues.build(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to [:admin, @league], notice: 'League was successfully created.' }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/leagues/1
  # PUT /admin/leagues/1.json
  def update
    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to [:admin, @league], notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/leagues/1
  # DELETE /admin/leagues/1.json
  def destroy
    @league.destroy

    respond_to do |format|
      format.html { redirect_to admin_leagues_url }
      format.json { head :no_content }
    end
  end

private

  def find_league
    @league = @sport.leagues.find_by_slug(params[:id])
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/admin/leagues/_form.html.erb
<%= simple_form_for([:admin, @league], :html => { :class => 'form-horizontal' }, :defaults => { :input_html => { :class => 'input-medium' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :abbreviation %>
    <%= f.association :sport %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/admin/leagues/edit.html.erb
<div class="page-header">
  <%= link_to admin_sports_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to [:admin, @sport], :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1><%= @sport.name %>: <%= @league.name %></h1>
</div>

<%= render 'form' %>

app/views/admin/leagues/index.html.erb
<div class="page-header">
  <%= link_to new_admin_league_path, :class => 'btn btn-success' do %>
    <i class="icon-plus icon-white"></i>
    Add
  <% end %>
  <h1><%= @sport.name %>: Leagues</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= link_to league.name, admin_league_path(league) %></td>
        <td><%= link_to league.abbreviation, admin_league_path(league) %></td>
        <td>
          <%= link_to 'e', [:admin, league] %>
          <%= link_to 'x', [:admin, league], confirm: 'Are you sure?', method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/leagues/new.html.erb
<div class="page-header">
  <%= link_to admin_leagues_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>Add a league</h1>
</div>

<%= render 'form' %>

app/views/admin/leagues/show.html.erb
<div class="page-header">
  <%= link_to admin_sports_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_admin_sport_path(@sport), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1><%= @sport.name %></h1>
</div>

<div class="page-header">
  <%= link_to new_admin_league_path(:sport => @sport), :class => 'btn btn-success' do %>
    <i class="icon-plus icon-white"></i>
    Add
  <% end %>
  <h2>Leagues</h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sport.leagues.each do |league| %>
      <tr>
        <td><%= link_to league.name, edit_admin_league_path(league) %></td>
        <td><%= link_to league.abbreviation, edit_admin_league_path(league) %></td>
      </tr>
    <% end %>
  </tbody>
</table>