config/routes.rb
DreamTeam::Application.routes.draw do

  # Admin-only routes
  unless Rails.env.production?
    namespace :admin do
      root :to => "sports#index"
      resources :sports
      resources :projects
      resources :picks
      resources :readers
      resources :unit_actions

      scope ":sport" do
        resources :leagues
        resources :conferences
        resources :divisions
        resources :teams
        resources :players
      end
    end
  end


  scope ":project" do
    resources :picks
    post "picks/update", :to => "picks#update", :as => "update_picks"
    resources :readers
    resources :players
    resources :teams

  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :pick_windows
  attr_accessible :name, :slug
  validates_uniqueness_of :slug

  # If today is within a pick window, return it.
  # Otherwise, return nil.
  def current_pick_window
    pick_windows.where("window_start < '#{DateTime.now}' AND window_end > '#{DateTime.now}'").first
  end

  def to_param
    slug
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :find_project, :except => [:index, :new, :create]

  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /admin/projects/new
  # GET /admin/projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /admin/projects/1/edit
  def edit
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/projects/1
  # PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to admin_projects_url }
      format.json { head :no_content }
    end
  end

private

  def find_project
    @project = Project.find_by_slug(params[:project])
  end
end

app/views/admin/projects/_form.html.erb
<%= simple_form_for([:admin, @team], :defaults => { :input_html => { :class => 'input-xlarge' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :league %>
    <%= f.input :conference %>
    <%= f.input :division %>
    <%= f.input :abbreviation %>
    <%= f.input :location %>
    <%= f.input :color %>
    <%= f.input :source_id, :label => "Source ID" %>
    <%= f.input :source %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="page-header">
  <%= link_to admin_teams_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to [:admin, @team], :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1><%= @team.name_and_location %>: edit</h1>
</div>

<%= render 'form' %>

app/views/admin/projects/index.html.erb
<div class="page-header">
  <%= link_to new_admin_project_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New project
  <% end %>
  <h1>projects</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, admin_project_path(project) %></td>
        <td>
          <%= link_to 'e', [:admin, project] %>
          <%= link_to 'x', [:admin, project], confirm: 'Are you sure?', method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/projects/new.html.erb
<div class="page-header">
  <%= link_to admin_teams_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New Team</h1>
</div>

<%= render 'form' %>

app/views/admin/projects/show.html.erb
<div class="page-header">
  <%= link_to admin_teams_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_admin_team_path(@team), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1><%= @team.name_and_location %></h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @team.players.each do |player| %>
      <tr>
        <td>
          <%= link_to player.full_name, edit_admin_player_path(player) %>
        </td>
        <td>
          <span class="badge <%= player.badge_color %>" title="<%= player.position_name %>"><%= player.position %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>