config/routes.rb
DreamTeam::Application.routes.draw do

  # Admin-only routes
  unless Rails.env.production?
    namespace :admin do
      root :to => "sports#index"
      resources :sports
      resources :projects
      resources :picks
      resources :readers
      resources :unit_actions

      scope ":sport" do
        resources :leagues
        resources :conferences
        resources :divisions
        resources :teams
        resources :players
      end
    end
  end


  scope ":project" do
    resources :picks
    post "picks/update", :to => "picks#update", :as => "update_picks"
    resources :readers
    resources :players
    resources :teams

  end

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :name, :slug
  has_many :leagues

  include Sluggish
end

app/controllers/admin/sports_controller.rb
class Admin::SportsController < Admin::ApplicationController

  before_filter :find_sport, :except => [:index, :new, :create]
  # GET /admin/sports
  # GET /admin/sports.json
  def index
    @sports = Sport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sports }
    end
  end

  # GET /admin/sports/1
  # GET /admin/sports/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /admin/sports/new
  # GET /admin/sports/new.json
  def new
    @sport = Sport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sport }
    end
  end

  # GET /admin/sports/1/edit
  def edit
  end

  # POST /admin/sports
  # POST /admin/sports.json
  def create
    @sport = Sport.new(params[:sport])

    respond_to do |format|
      if @sport.save
        format.html { redirect_to [:admin, @sport], notice: 'Sport was successfully created.' }
        format.json { render json: @sport, status: :created, location: @sport }
      else
        format.html { render action: "new" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/sports/1
  # PUT /admin/sports/1.json
  def update
    respond_to do |format|
      if @sport.update_attributes(params[:sport])
        format.html { redirect_to [:admin, @sport], notice: 'Sport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sports/1
  # DELETE /admin/sports/1.json
  def destroy
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to admin_sports_url }
      format.json { head :no_content }
    end
  end

private

  def find_sport
    @sport = Sport.find_by_slug(params[:id])
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/admin/sports/_form.html.erb
<%= simple_form_for([:admin, @sport], :html => { :class => 'form-horizontal' }, :defaults => { :input_html => { :class => 'input-medium' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :placeholder => "Sport name" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/admin/sports/edit.html.erb
<div class="page-header">
  <%= link_to admin_sports_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to [:admin, @sport], :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1><%= @sport.name %>: edit</h1>
</div>

<%= render 'form' %>

app/views/admin/sports/index.html.erb
<div class="page-header">
  <%= link_to new_admin_sport_path, :class => 'btn btn-success' do %>
    <i class="icon-plus icon-white"></i>
    Add
  <% end %>
  <h1>Sports</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= link_to sport.name, admin_sport_path(sport) %></td>
        <td>
          <%= link_to 'e', [:admin, sport] %>
          <%= link_to 'x', [:admin, sport], confirm: 'Are you sure?', method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/sports/new.html.erb
<div class="page-header">
  <%= link_to admin_sports_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>Add a Sport</h1>
</div>

<%= render 'form' %>

app/views/admin/sports/show.html.erb
<div class="page-header">
  <%= link_to admin_sports_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_admin_sport_path(@sport), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <%= link_to new_admin_league_path(:sport => @sport), :class => 'btn btn-success' do %>
    <i class="icon-plus icon-white"></i>
    Add League
  <% end %>
  <h1><%= @sport.name %> Leagues</h1>
</div>

<% @sport.leagues.each do |league| %>
  <h3><%= "#{league.name} (#{league.abbreviation})" %></h3>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Conferences
          <%= link_to new_admin_conference_path(:league => league), :class => 'btn btn-success btn-mini' do %>
            <i class="icon-plus icon-white"></i>
          <% end %>
        </th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% league.conferences.each do |conference| %>
        <tr>
          <td><%= link_to "#{conference.name} (#{conference.abbreviation})", edit_admin_conference_path(conference) %></td>
          <td>
            <%= conference.divisions.size %> divisions
            <%= link_to new_admin_division_path(:conference => conference), :class => 'btn btn-success btn-mini' do %>
              <i class="icon-plus icon-white"></i>
            <% end %>
          </td>
        </tr>
        <% if conference.divisions.any? %>
          <% conference.divisions.each do |division| %>
            <tr>
              <td><%= link_to division.name, edit_admin_division_path(division) %></td>
              <td>
                <%= division.teams.size %> teams
              </td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>